[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino

monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

lib_deps =
    m5stack/M5Atom @ ^0.1.0
    fastled/FastLED @ ^3.6.0
    emelianov/modbus-esp8266 @ ^4.1.0
    ftservo/FTServo

build_flags =
    -DARDUINO_M5Stack_ATOM
